### ISSUE TITLE
ex3

### ISSUE THREAD

**Issue by spencermathews** [mcolato8/ex1#1]
Where is ex3? Link to it from Portal?
Remember it needs to be in its own repository.

**Comment by mcolato8** [comment]
Hello Spencer, I was having trouble linking this but I'll be updating it
right now. I'll email you if I have questions. Also, are you free between
12-3pm tomorrow?

Thank you,

Michelle Colato-Ochoa

On Mon, Feb 1, 2016 at 4:07 PM, spencermathews notifications@github.com
wrote:

> Where is ex3? Link to it from Portal?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mcolato8/ex1/issues/1.

## 

Michelle Colato-Ochoa

**Comment by spencermathews** [comment]
Closing to clean up open issues.
